version: '3.8'

services:
  web:
    build: .
    command: python /dockerize-dj/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=django-insecure-cffj_2zrhvf-e6hbb86fbwg!rh*83=o&6o#=v87r7i3jc(xd+b
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    volumes:
      - .:/dockerize-dj
    ports:
      - 8000:8000
    
    depends_on:
      - redis
      - db

  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
  
  celery:
    build: .
    command: celery -A dockerizeDJ worker --loglevel=info
    volumes:
      - .:/dockerize-dj

    environment:
      - SECRET_KEY=django-insecure-cffj_2zrhvf-e6hbb86fbwg!rh*83=o&6o#=v87r7i3jc(xd+b
      - DEBUG=1
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
              
    depends_on:
      - web
      - db
      - redis

  redis:
    image: redis:6
  
  dashboard:
    build: .
    command: celery -A dockerizeDJ --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - db
      - redis
      - celery
volumes:
  postgres_data: