version: '3.8'

services:
  web:
    build: .
    command: python /dockerize-dj/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/dockerize-dj
    ports:
      - 8000:8000
    
    depends_on:
      - db

  db:
    image: postgres:14
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"