# Generated by Django 4.0.4 on 2022-05-19 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='cover',
            field=models.ImageField(blank=True, upload_to='covers/'),
        ),
    ]
