# Generated by Django 4.0.4 on 2022-05-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_item_cover'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_images',
            field=models.ImageField(blank=True, null=True, upload_to='product_images/'),
        ),
    ]
