# Generated by Django 4.0.4 on 2022-05-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_item_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_images',
            field=models.ImageField(blank=True, upload_to='product_images/'),
        ),
    ]
